// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzkhsqyinrdbajjvlgzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6a2hzcXlpbnJkYmFqanZsZ3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODE3MDYsImV4cCI6MjA1NjQ1NzcwNn0.8EJp44hi20t-_P33_9F_a1EJBqYWGrSst7cQaI2_N50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);